name: Extract and push zipped files

on:
  push:
    branches:
      - unzipped

jobs:
  extract_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Move folders with .os files
      run: |
        cd ${{ github.workspace }}
        find . -maxdepth 2 -type d -exec sh -c '
        for folder do
          if [ -z "$(find "$folder" -name "*.os" -type f)" ]; then
            echo "No .os file found in $folder, skipping move operation."
          else
            folder_name=$(basename "$folder")
            echo "Moving contents of folder $folder_name"
            if [ ! -d "ds/track" ]; then
              mv "$folder"/* ds/
            else
              echo "ds/track folder already exists, skipping move operation."
            fi
            break
          fi
        done' sh {} +
    
    - name: Commit changes
      run: |
        git add .
        git commit -m "Move folders with .os files"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "codeberg"

    - name: Push changes to unzipped branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: unzipped
        force: true
