name: Extract and push zipped files

on:
  push:
    branches:
      - unzipped

jobs:
  extract_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Extract zipped files
      run: |
        find . -name "*.zip" -exec unzip -o -d . {} \;
        rm -rf dm bt exp test server-sp-sounds user-server
    - name: Push changes to unzipped branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: unzipped
        force: true
