name: Extract and push zipped files

on:
  push:
    branches:
      - unzipped

jobs:
  extract_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Extract zipped files
      run: |
        #find . -name "*.zip" -exec unzip -o -d . {} \;
        #rm -rf dm bt exp test server-sp-sounds user-server tgw
        # Define the source directory as the current directory
        source_dir="."

        # Define the destination directory as a "ds" folder in the current directory
        dest_dir="./ds"

        # Check if the destination directory exists, if not, create it
        if [ ! -d "$dest_dir" ]; then
          echo "Creating destination directory: $dest_dir"
          mkdir "$dest_dir"
        fi

        # Find folders containing files with "os" in their names in the source directory,
        # excluding the current directory (".")
        folders=$(find "$source_dir" -mindepth 1 -type d ! -path "$source_dir" -name "*os*" -print0)

        # Loop through the found folders and move them to the destination directory
        while IFS= read -r -d $'\0' folder; do
          echo "Moving folder: $folder"
          mv "$folder" "$dest_dir/"
        done <<< "$folders"

        echo "Folders containing 'os' files have been moved to $dest_dir."


        git add -A
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "codeberg"
        git commit -m "move os dirs to ds folder"
    - name: Push changes to unzipped branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: unzipped
        force: true
