name: Extract and push zipped files

on:
  push:
    branches:
      - unzipped

jobs:
  extract_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Move folders with .os files
      run: |
        source_dir="."
        ds_dir="ds"

        # Get a list of all folders in the source directory (excluding the source directory itself)
        folders=$(find "$source_dir" -type d -maxdepth 1 -mindepth 1)

        # Loop through each folder
        for folder in $folders; do
          # Check if the folder contains .os files
          if [ "$(find "$folder" -name "*.os" -type f)" ]; then
            # Extract the folder name without the full path
            folder_name=$(basename "$folder")

            # Check if the folder already exists inside ds_dir
            if [ -d "$ds_dir/$folder_name" ]; then
              # Move the .os files inside the existing ds_dir/folder_name
              mv "$folder"/*.os "$ds_dir/$folder_name/"
            else
              # Move the entire folder to ds_dir
              mv "$folder" "$ds_dir/"
            fi
          fi
        done
    
    - name: Commit changes
      run: |
        git add .
        git commit -m "Move folders with .os files"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "codeberg"

    - name: Push changes to unzipped branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: unzipped
        force: true
